/* eslint-disable import/no-relative-packages */
// roboto
import '../node_modules/@fontsource/roboto/index.css';
import '../node_modules/@fontsource/roboto/100.css';
import '../node_modules/@fontsource/roboto/100-italic.css';
import '../node_modules/@fontsource/roboto/300.css';
import '../node_modules/@fontsource/roboto/300-italic.css';
import '../node_modules/@fontsource/roboto/400.css';
import '../node_modules/@fontsource/roboto/400-italic.css';
import '../node_modules/@fontsource/roboto/500.css';
import '../node_modules/@fontsource/roboto/500-italic.css';
import '../node_modules/@fontsource/roboto/700.css';
import '../node_modules/@fontsource/roboto/700-italic.css';
import '../node_modules/@fontsource/roboto/900.css';
import '../node_modules/@fontsource/roboto/900-italic.css';
// fontawesome
import '../node_modules/@fortawesome/fontawesome-free/css/fontawesome.min.css';
// others
import './vars.css';
import './global-styles.scss';
