/* eslint-disable import/no-relative-packages */
import '../node_modules/reset-css/reset.css';
// inter
import '../node_modules/@fontsource/inter/index.css';
import '../node_modules/@fontsource/inter/100.css';
import '../node_modules/@fontsource/inter/300.css';
import '../node_modules/@fontsource/inter/400.css';
import '../node_modules/@fontsource/inter/500.css';
import '../node_modules/@fontsource/inter/700.css';
import '../node_modules/@fontsource/inter/900.css';
// open-sans
import '../node_modules/@fontsource/open-sans/index.css';
import '../node_modules/@fontsource/open-sans/300.css';
import '../node_modules/@fontsource/open-sans/300-italic.css';
import '../node_modules/@fontsource/open-sans/400.css';
import '../node_modules/@fontsource/open-sans/400-italic.css';
import '../node_modules/@fontsource/open-sans/500.css';
import '../node_modules/@fontsource/open-sans/500-italic.css';
import '../node_modules/@fontsource/open-sans/600.css';
import '../node_modules/@fontsource/open-sans/600-italic.css';
import '../node_modules/@fontsource/open-sans/700.css';
import '../node_modules/@fontsource/open-sans/700-italic.css';
import '../node_modules/@fontsource/open-sans/800.css';
import '../node_modules/@fontsource/open-sans/800-italic.css';
//fira-mono
import '../node_modules/@fontsource/fira-mono/index.css';
import '../node_modules/@fontsource/fira-mono/400.css';
import '../node_modules/@fontsource/fira-mono/500.css';
import '../node_modules/@fontsource/fira-mono/700.css';
// poppins
import '../node_modules/@fontsource/poppins/index.css';
import '../node_modules/@fontsource/poppins/100.css';
import '../node_modules/@fontsource/poppins/100-italic.css';
import '../node_modules/@fontsource/poppins/200.css';
import '../node_modules/@fontsource/poppins/200-italic.css';
import '../node_modules/@fontsource/poppins/300.css';
import '../node_modules/@fontsource/poppins/300-italic.css';
import '../node_modules/@fontsource/poppins/400.css';
import '../node_modules/@fontsource/poppins/400-italic.css';
import '../node_modules/@fontsource/poppins/500.css';
import '../node_modules/@fontsource/poppins/500-italic.css';
import '../node_modules/@fontsource/poppins/600.css';
import '../node_modules/@fontsource/poppins/600-italic.css';
import '../node_modules/@fontsource/poppins/700.css';
import '../node_modules/@fontsource/poppins/700-italic.css';
import '../node_modules/@fontsource/poppins/800.css';
import '../node_modules/@fontsource/poppins/800-italic.css';
// roboto
import '../node_modules/@fontsource/roboto/index.css';
import '../node_modules/@fontsource/roboto/100.css';
import '../node_modules/@fontsource/roboto/100-italic.css';
import '../node_modules/@fontsource/roboto/300.css';
import '../node_modules/@fontsource/roboto/300-italic.css';
import '../node_modules/@fontsource/roboto/400.css';
import '../node_modules/@fontsource/roboto/400-italic.css';
import '../node_modules/@fontsource/roboto/500.css';
import '../node_modules/@fontsource/roboto/500-italic.css';
import '../node_modules/@fontsource/roboto/700.css';
import '../node_modules/@fontsource/roboto/700-italic.css';
import '../node_modules/@fontsource/roboto/900.css';
import '../node_modules/@fontsource/roboto/900-italic.css';
// fontawesome
import '../node_modules/@fortawesome/fontawesome-free/css/fontawesome.min.css';
// others
import '../node_modules/react-multi-date-picker/styles/layouts/mobile.css';
import './vars.css';
import './global-styles.scss';
