name: Deploy Prepatch

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test
    - run: npm run lint
    - run: npm run build
    - run: npx standard-version --prerelease
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
